# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SwiftSideMenu' do
  pod 'CorePlot'
	pod 'JBChartView'
# https://github.com/Alamofire/Alamofire
  pod 'Alamofire', '~> 3.0'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  # https://github.com/modocache/MDCSwipeToChoose
   pod "MDCSwipeToChoose"
   # https://github.com/rs/SDWebImage
    pod 'SDWebImage', '~>3.7'

    # https://github.com/SwiftyJSON/SwiftyJSON$

    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'EAIntroView', '~> 2.7.0'
    pod 'RKNotificationHub' 


    end

    target 'SwiftSideMenuTests' do

    end

